### ISSUE TITLE
working across mutliple Projects

### ISSUE THREAD

**Issue by BC14w** [unacast/bigquerylayers#14]
I'm wondering if it would be possible to query across multiple projects like it can be done directly on bigquery? for example if i'm querying something like this:
`select * from 'project_1.data_1' where x in (select y from 'project_2.data_2')` 
Right now it seems there is only one project that can placed as input for the Project section. Would it be possible to have the input of Project something like this:
`project_1, project_2`

**Comment by smandaric** [comment]
You can query across multiple project by adding project name in your FROM statement like this:
`select * from 'project_1.dataset_1.table_1' where x in (select y from 'project_2.dataset_2.table_2')`
