### ISSUE TITLE
Download as .SHP 

### ISSUE THREAD

**Issue by jorgenbraseth** [unacast/bigquerylayers#6]
For large datasets, putting it all in memory can be unviable. Saving the output from BQ in a .shp file (or other indexed format) would make this kind of workflow easier.

Saving the ressults to files also prevent data loss (with a subsequent need for pulling all the data from BQ again) on a crash.

**Comment by smandaric** [comment]
I will experiment with converting the data to GeoPackage before layer import. This should add a layer index.
