### ISSUE TITLE
Cannot run query on Windows 10

### ISSUE THREAD

**Issue by JvBremen** [unacast/bigquerylayers#9]
Thank you for providing the PlugIn! :-)
Unfortunately there is a little problem: I did GClould Auth flow and installed the plugin via zip-installer. When running a query I get 'Errors in base query'. The exact same query works when running it in the BigQuery UI.
Are the any tips regarding debugging or is it a Windows problem?
Thx in advance and have a nice day,
Johannes

**Comment by smandaric** [comment]
Thanks for reporting this. I have only tested the plugin on Mac so this may be a Windows issue. 

I would start by checking if a query is triggered when the run button is pressed. You can see this in the BigQuery UI, under Query history

**Comment by smandaric** [comment]
The issue appears to be authentication on Windows. Try generating credentials for client libraries by running 

`gcloud auth application-default login`

**Comment by JvBremen** [comment]
Hi Stefan,
thank you very much for you reply! It finally worked and the query went through but when adding the result (geo_location) an error occurs displaying 'layer is invalid: selected field is not a layer and cannot be added to the map. Reason:'
For Mac everything works just fine but for Windows (QGIS versions 3.4.4 and 3.6.1) it fails.
Do you by chance have any further idea?
Have a good day and best wishes,
Johannes

**Comment by judoole** [comment]
@JvBremen did the "Reason" part get lost or was `Reason:'`?

**Comment by smandaric** [comment]
@JvBremen It seems to be a Windows path issue. Can you confirm that the pull request solves the issue?

**Comment by JvBremen** [comment]
Hi Stefan,
sorry for the late reply! Just wanted to let you know that everything is working fine now... :-)
BIG Thanks for your support!
